/**
 * @license MIT
 * @author https://github.com/libertypie
 * This file was auto generated by tools/watcher.js
 * do not edit this, edit src/styles/main.scss rather
 */
declare let styleData: string;
export default styleData;
