
        /**
         * @license MIT 
         * @author https://github.com/libertypie
         * This file was auto generated by tools/watcher.js
         * do not edit this, edit src/styles/main.scss rather
         */

        let styleData = `.brave_16_icon{background-image:url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAulBMVEUAAADxVCvpSCjhPCbxVSvxVSvgPCbxVivfPCbxVSvgPCboSSjxUSrjPCbxVCvhPCbvRynsPyngPCbfPCbgPCbxUyvhPCbxVSvgPCbxVivfPCb////hPCbxVSvxUyvwTyrmPSf+9PL3nYjwRyrsPyn83df7yL33w7z6v7D5uK/2lHv708r5z8n0tq7yqqDukYXshXf1iG3jSDT6w7z4rqL2q6H4p5X2n5TynpPtkYXtemvza0bkVEHyXjh9kLt/AAAAG3RSTlMA7zDv37+/n5+Pj2BQUBAQ7+/v38+vr4CAICABrmMIAAAAr0lEQVQY0y2PVQLDMAxD0zEzy8nWbuV2hTHd/1oLVH9+tmyLKdWs/fF0qNeY0bppCQWo3tqousu5ExVh+M4zop4EbR6hUkYdCZofG8HdxjMFvi0JGgWAGPABvObaEgAekACptvQ59xB7YQKfqC/BVl4B3AtwJtoxtUQC+/qwJVgw84iIXMDNS+ppMODiFwB+STTUYGQJsXduB6LZmJlsVRadzswsFVhVfbNnMjV+9gcQXBUQsXO9fwAAAABJRU5ErkJggg==")}`;
        export default styleData;
        