
        /**
         * @license MIT 
         * @author https://github.com/libertypie
         * This file was auto generated by tools/watcher.js
         * do not edit this, edit src/styles/main.scss rather
         */

        let styleData = `.status_16_icon{background-image:url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAMFBMVEUAAABbbe5bbe5bbe5bbe5bbe5bbe7////W2/t6iPHM0fq3v/ittveOm/OEkvJwf/DcYthnAAAABnRSTlMAz79gIO+tFDY8AAAAbklEQVQI12NgYDBKS1NmAALHNCAQYWBgCQMxUh0YGIFU3rQ0AQaztLSc8qq0ZAa1tLTt5eVpSQxpafnlQEYakJHZ0dELZtzo6JgGZgBlvgEZakBGdVpaElD78vJjaUDtjGmZz4BmCsCtgFsKdwYAndQtXIEfsPUAAAAASUVORK5CYII=")}`;
        export default styleData;
        